apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "10s"
      httpMethod: POST

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-ds
    access: proxy
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: imdb
      username: default
    secureJsonData:
      password: clickhouse
